package com.xcesys.extras.framework.entity;

import javax.persistence.Entity;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.xcesys.extras.framework.dao.model.IdAuditableEntity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Dict generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor
@Getter
@Setter
public class Dict extends IdAuditableEntity implements java.io.Serializable {

	private static final long serialVersionUID = -8572522105499245114L;
	private String description;
	private Long id;
	private String name;
	private Integer seq;
	private DictType dictType;
	private Long dictTypeId;
	private String value;

}
