package com.xcesys.extras.framework.entity;

// Generated 2010-11-3 20:32:38 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.xcesys.extras.framework.dao.model.IdAuditableEntity;

import lombok.Getter;
import lombok.Setter;

/**
 * DictType generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@Getter
@Setter
public class DictType extends IdAuditableEntity {

	private static final long serialVersionUID = -4470144171936304544L;
	private String description;
	private Integer length;
	private Set<Dict> dicts = new HashSet<Dict>(0);
	private Boolean editable;

}
