package com.xcesys.extras.framework.entity;

// Generated 2010-11-24 16:30:46 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.xcesys.extras.framework.dao.model.IdTreeEntity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Menu generated by hbm2java
 */
//@Entity
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor
@Getter
@Setter
public class Menu extends IdTreeEntity<Menu> implements java.io.Serializable {
	private static final long serialVersionUID = -2166097395146569342L;
	private String actionName;
	private String cssClass;
	private String description;
	private Boolean editable = Boolean.TRUE;
	private String forewardName;
	private String icon;
	private String iconClass;
	private String image16;
	private String image24;
	private String image32;
	private String image48;
	private String params;
	private Boolean published;
	private String title;
	private String tooltip;
	private Permission permission;
	private Long permissionId;
	private String url;

	@Column(name = "ACTION_NAME", length = 100)
	public String getActionName() {
		return actionName;
	}

	@Column(name = "CSS_CLASS", length = 100)
	public String getCssClass() {
		return cssClass;
	}

	@Column(name = "DESCRIPTION", length = 800)
	public String getDescription() {
		return this.description;
	}

	@Override
	@Transient
	public String getDisplayName() {
		if (this.depth > 1) {
			this.displayName = StringUtils.leftPad("　　", this.depth - 1) + "－" + this.title;
		} else {
			this.displayName = "+ " + this.title;
		}
		return displayName;
	}

	@Column(name = "EDITABLE", length = 1)
	public Boolean getEditable() {
		return this.editable;
	}

	@Column(name = "FOREWARD_NAME", length = 100)
	public String getForewardName() {
		return forewardName;
	}

	@Column(name = "ICON", length = 50)
	public String getIcon() {
		return icon;
	}

	@Column(name = "ICON_CLASS", length = 50)
	public String getIconClass() {
		return iconClass;
	}

	@Column(name = "IMAGE16", length = 255)
	public String getImage16() {
		return this.image16;
	}

	@Column(name = "IMAGE24", length = 255)
	public String getImage24() {
		return image24;
	}

	@Column(name = "IMAGE32", length = 255)
	public String getImage32() {
		return image32;
	}

	@Column(name = "IMAGE48", length = 255)
	public String getImage48() {
		return image48;
	}

	@Override
	@Transient
	public String getLineage() {
		this.lineage = (this.parent == null ? "0" : this.parent.getLineage())
				+ (this.seq == null ? "" : ("_" + StringUtils.leftPad("0", 3) + "" + this.seq)) + "." + this.getId();
		return this.lineage;
	}

	@Column(name = "PARAMS", length = 200)
	public String getParams() {
		return params;
	}

	@Column(name = "PUBLISHED", length = 1)
	public Boolean getPublished() {
		return published;
	}

	@Column(name = "TITLE", nullable = false, length = 400)
	public String getTitle() {
		return this.title;
	}

	@Column(name = "TOOLTIP", length = 400)
	public String getTooltip() {
		return this.tooltip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_ID", insertable = false, updatable = false)
	public Permission getPermission() {
		return this.permission;
	}

	@Column(name = "PERMISSION_ID", precision = 20, scale = 0)
	public Long getPermissionId() {
		return permissionId;
	}

	@Column(name = "URL", length = 255)
	public String getUrl() {
		return this.url;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public void setCssClass(String cssClass) {
		this.cssClass = cssClass;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setEditable(Boolean editable) {
		this.editable = editable;
	}

	public void setForewardName(String foreward) {
		this.forewardName = foreward;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public void setIconClass(String iconClass) {
		this.iconClass = iconClass;
	}

	public void setImage16(String image) {
		this.image16 = image;
	}

	public void setImage24(String image24) {
		this.image24 = image24;
	}

	public void setImage32(String image32) {
		this.image32 = image32;
	}

	public void setImage48(String image48) {
		this.image48 = image48;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public void setPublished(Boolean published) {
		this.published = published;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return name + "," + title;
	}
}
