package com.xcesys.extras.framework.entity;

// Generated 2010-11-25 11:58:51 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.xcesys.extras.framework.dao.model.IdAuditableEntity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Permission generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor
@Getter
@Setter
public class Permission extends IdAuditableEntity implements java.io.Serializable {

	private static final long serialVersionUID = 3376006942984531464L;
	private String aclPattern;
	private String actionName;
	// private Set<Permission> dependsPermissions = new HashSet<Permission>(0);
	private String description;
	private String name;
	private Long requireId;
	// private Permission requirePermission;
	// private Set<Menu> tsMenus = new HashSet<Menu>(0);
	private Module module;
	private Long moduleId;
	private Set<Role> roles = new HashSet<Role>(0);
	private Subsystem subsystem;
	private Long subsystemId;
	private Set<User> users = new HashSet<User>(0);
	protected String displayName;

	@Transient
	public String getDisplayName() {
		if (!StringUtils.isBlank(this.displayName)) {
			return this.displayName;
		}
		if (this.module != null) {
			this.displayName = this.module.getTreeName() + ">" + this.name;
		} else {
			this.displayName = this.name;
		}
		return displayName;
	}

}
