package com.xcesys.extras.framework.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.xcesys.extras.framework.dao.model.IdAuditableEntity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;

/**
 * Setting generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor
@Getter
@Setter
public class Setting extends IdAuditableEntity implements java.io.Serializable {

	private static final long serialVersionUID = 4695202659405293403L;
//	@ManyToOne
//	private Module module;
	@Column(unique = true)
	@NonNull
	private String name;
	private String description;
	private String type;
	private String value;
	private String credentials;

}
